# Generated by Django 4.0 on 2022-08-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="departement",
            new_name="department",
        ),
    ]
