# Generated by Django 4.0 on 2022-08-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_client_contact"),
        ("users", "0006_rename_departement_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="crm.department",
            ),
        ),
    ]
