# Generated by Django 4.0 on 2022-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("fix_phone", models.CharField(max_length=10)),
                ("mobile_phone", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("PO", "Potential"), ("AC", "Actual")], max_length=2
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("company", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
