# Generated by Django 4.0 on 2022-08-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="company",
        ),
    ]
