# Generated by Django 4.0 on 2022-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "field_error",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name_error", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
