# Generated by Django 4.0 on 2022-09-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_log"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="field_error",
            new_name="error_field",
        ),
        migrations.RenameField(
            model_name="log",
            old_name="name_error",
            new_name="error_name",
        ),
    ]
