# Generated by Django 4.0 on 2022-08-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_departement_user_department"),
        ("crm", "0005_client_company_client_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="users.user",
            ),
            preserve_default=False,
        ),
    ]
