# Generated by Django 4.0 on 2022-09-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_log_date_log_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="error_field",
            new_name="field",
        ),
        migrations.RenameField(
            model_name="log",
            old_name="error_name",
            new_name="message",
        ),
        migrations.AddField(
            model_name="log",
            name="model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
