# Generated by Django 4.0 on 2022-08-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_departement_user_department"),
        ("crm", "0007_alter_client_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.user",
            ),
        ),
    ]
