# Generated by Django 4.0 on 2022-08-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_client_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="department",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("POTENTIAL", "Potential"), ("ACTUAL", "Actual")],
                max_length=255,
            ),
        ),
    ]
