# Generated by Django 4.0 on 2022-08-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_rename_department_department_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("POTENTIAL", "Potential"), ("ACTUAL", "Actual")],
                default="POTENTIAL",
                max_length=255,
            ),
        ),
    ]
