# Generated by Django 4.0 on 2022-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_alter_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="fix_phone",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile_phone",
            field=models.CharField(max_length=12),
        ),
    ]
