# Generated by Django 4.0 on 2022-08-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_department"),
        ("crm", "0012_alter_client_fix_phone_alter_client_mobile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.user",
            ),
        ),
    ]
