# Generated by Django 4.0 on 2022-08-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_alter_client_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="date_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
