# Generated by Django 4.0 on 2022-08-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_alter_client_date_created_alter_client_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
