# Generated by Django 4.0 on 2022-08-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_alter_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="fix_phone",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile_phone",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
