# Generated by Django 4.0 on 2022-08-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_department"),
        ("crm", "0017_alter_client_contact_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="crm.client"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendees", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contract"
                    ),
                ),
            ],
        ),
    ]
