# Generated by Django 4.0 on 2022-09-02 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_department"),
        ("crm", "0018_contract_client_alter_client_contact_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
